language: java
jdk:
  - openjdk11
stages:
  - name: compile
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master

jobs:
  include:
    - stage: compile
      language: java
      install: true
      os: linux
      dist: trusty
      jdk: openjdk11
      script:
        - ./gradlew buildPlugin
    - stage: deploy
      script:
        - ./gradlew publishPlugin