sudo: required
services:
  - docker

stages:
  - name: compile
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master

jobs:
  include:
    - stage: compile
      language: java
      install: true
      os: linux
      dist: trusty
      jdk: oraclejdk8
      script:
        - ./gradlew clean assemble
    - stage: deploy
      on:
        branch: master